resource "aws_api_gateway_api_key" "A_Demo_Key" {
  name = "demo purpose"   // it is required
  description = "it is again optional"
  enabled = false   // by defaults to true
  value = "SDFHJH22345678VHGHU"   // it is again optional, it is automatically generated by AWS on creation
  tags = {} // again it is optionals

}